import os
import pytest
import pandas as pd
from dd_parser.core import LocalEntityClassifier
from dd_cleaner.engine import DatasetCleaner

def test_cleaner_pipeline_execution(managed_test_config):
    """
    Validates end-to-end data scrubbing routines across any format.
    Checks state change operations rather than matching hardcoded record values.
    """
    # 1. Step 1: Run the Case-Preserving Parser
    parser_classifier = LocalEntityClassifier()
    parser_classifier.set_working_config(working_dir="./tests", config_path=managed_test_config)
    parser_classifier.process_pipeline()

    # 2. Step 2: Extract the exact casing dictionary mapping generated by the parser
    raw_attributes = parser_classifier.extract_inventory_attributes()
    case_insensitive_lookup = {attr.lower(): attr for attr in raw_attributes}

    # 3. Step 3: Trigger the downstream cleaning engine
    cleaner = DatasetCleaner()
    cleaner.set_working_config(working_dir="./tests", config_path=managed_test_config)

    resolver = cleaner.paths

    # Establish independent verification sidecar handshake
    meta_csv_path = resolver.data_dictionary_csv_path
    with open(f"{meta_csv_path}.signature", "w", encoding='utf-8') as f:
        f.write("# DD-PARSER-SIGNATURE: PROCESSED-BY-LLAMA3.2\n")

    print("\n🚀 Executing geographic transformation checks...")
    cleaner.process_cleaning_pipeline()

    # 🧼 FIX: Trust the authoritative config file path properties directly 
    # instead of expecting hardcoded/unaligned 'data_cleaner_dir' attributes
    expected_clean_csv = resolver.clean_dataset_output_path

    # Structural Checkpoints
    assert os.path.exists(expected_clean_csv), f"❌ Cleaned target matrix missing at: {expected_clean_csv}"

    # Verify structural integrity
    df_clean = pd.read_csv(expected_clean_csv)
    
    # Assert column case normalization matches what was expected from the lookup maps
    for col in df_clean.columns:
        if col.lower() in case_insensitive_lookup:
            assert col == case_insensitive_lookup[col.lower()], f"❌ Casing mutated downstream for column {col}"
