import os
import pandas as pd
from dd_parser.core import LocalEntityClassifier
from dd_cleaner.engine import DatasetCleaner

def test_cleaner_pipeline_execution(managed_test_config):
    """
    Validates end-to-end data scrubbing routines across any format.
    Checks state change operations rather than matching hardcoded record values.
    """
    # 1. Step 1: Run the Case-Preserving Parser
    parser_classifier = LocalEntityClassifier()
    parser_classifier.set_working_config(working_dir="./tests", config_path=managed_test_config)
    parser_classifier.process_pipeline()
    
    # 2. Step 2: Extract the exact casing dictionary mapping generated by the parser
    # This gives us the precise column structure of the raw file
    raw_attributes = parser_classifier.extract_inventory_attributes()
    case_insensitive_lookup = {attr.lower(): attr for attr in raw_attributes}
    
    # 3. Step 3: Trigger the down-stream cleaning engine
    cleaner = DatasetCleaner()
    cleaner.set_working_config(working_dir="./tests", config_path=managed_test_config)
    
    resolver = cleaner.paths
    clean_filename = cleaner.config.get("clean_output_filename", "sba_loans_clean.csv")
    
    # Establish independent verification sidecar handshake
    meta_csv_path = resolver.data_dictionary_csv_path
    with open(f"{meta_csv_path}.signature", "w", encoding='utf-8') as f:
        f.write("# DD-PARSER-SIGNATURE: PROCESSED-BY-LLAMA3.2\n")
    
    print("\n🚀 Executing geographic transformation checks...")
    cleaner.process_cleaning_pipeline()
    
    # Structural Checkpoints
    expected_clean_csv = os.path.join(resolver.data_cleaner_dir, clean_filename)
    expected_report_md = os.path.join(resolver.documents_dir, "data_cleaning_summary.md")
    
    assert os.path.exists(expected_clean_csv), f"❌ Clean dataset file missing at: {expected_clean_csv}"
    assert os.path.exists(expected_report_md), f"❌ Cleaning summary report missing at: {expected_report_md}"
    
    # 4. Step 4: Run Dynamic Structural Rules instead of hardcoded lookups
    df_clean = pd.read_csv(expected_clean_csv, dtype=str)
    
    # Find matching tracking elements natively within the specific file context
    city_col = case_insensitive_lookup.get("borrcity") or case_insensitive_lookup.get("thirdpartylender_city")
    zip_col = case_insensitive_lookup.get("cdc_zip") or case_insensitive_lookup.get("borrzip")
    
    # Verify processing logic principles dynamically if columns exist
    if city_col and city_col in df_clean.columns:
        for val in df_clean[city_col].dropna().head(5):
            assert val == str(val).title(), f"❌ Failure: Title-casing rules violated for value '{val}' in column '{city_col}'"
            
    if zip_col and zip_col in df_clean.columns:
        for val in df_clean[zip_col].dropna().head(5):
            if val.isdigit():
                assert len(val) == 5, f"❌ Failure: Zip padding rules violated for value '{val}' in column '{zip_col}'"
