"""
Test suite for validating provisional cleaning recommendations.
Simulates a 'Dry Run' of the Assistant's suggestions.
"""

import pytest
import pandas as pd
import yaml
import os
from pathlib import Path
from dd_cleaner.orchestrator import CleanerOrchestrator
from dd_cleaner.pipeline import PipelineRunner
from path_coordinator import PathCoordinator

def test_provisional_dry_run(managed_test_config):
    """
    Validates that the provisional_config.yaml generated by the Assistant
    is physically executable and produces a valid transformed dataset.
    """
    # 1. Setup Environment
    config_path = Path(managed_test_config).resolve()
    workspace = Path(os.getcwd()) / "tests"
    coord = PathCoordinator(config_path=config_path, working_dir=workspace)
    orch = CleanerOrchestrator(coord)

    # 2. Generate Recommendations
    orch.run_pipeline(action="assessment")
    
    prov_path = coord.cleaner_output_directory / "provisional_config.yaml"
    assert prov_path.exists(), "Assistant failed to generate provisional_config.yaml"

    # 3. Create a 'Sandbox Config'
    # We merge the provisional overrides into the base config for a full run
    with open(config_path, 'r') as f:
        base_cfg = yaml.safe_load(f)
    with open(prov_path, 'r') as f:
        prov_cfg = yaml.safe_load(f)

    # Apply provisional changes to base
    if "column_filters" in prov_cfg["cleaner"]:
        base_cfg["cleaner"]["column_filters"]["drop_attributes"] = \
            prov_cfg["cleaner"]["column_filters"].get("drop_attributes", [])
    
    if "missing_values" in prov_cfg["cleaner"]:
        base_cfg["cleaner"]["missing_values"]["attribute_overrides"] = \
            prov_cfg["cleaner"]["missing_values"].get("attribute_overrides", {})

    # Save as sandbox_config.yaml
    sandbox_cfg_path = coord.cleaner_output_directory / "sandbox_config.yaml"
    with open(sandbox_cfg_path, 'w') as f:
        yaml.safe_dump(base_cfg, f)

    # 4. Execute Sandbox Run
    sandbox_coord = PathCoordinator(config_path=sandbox_cfg_path, working_dir=workspace)
    runner = PipelineRunner(sandbox_coord)
    runner.run(action="full")

    # 5. Verify Results
    clean_file = base_cfg["cleaner"]["clean_output_filename"]
    result_path = sandbox_coord.cleaner_output_directory / clean_file
    
    assert result_path.exists(), "Sandbox run failed to produce output."
    
    df_result = pd.read_csv(result_path)
    
    # Check if a recommended drop was actually dropped
    recommended_drops = prov_cfg["cleaner"]["column_filters"].get("drop_attributes", [])
    for col in recommended_drops:
        assert col not in df_result.columns, f"Provisional drop failed for {col}"

    print(f"\n[PASS] Sandbox trial successful. Results at: {result_path}")