import os
import time
import logging
import yaml
import pandas as pd
from typing import Dict, Any
from path_coordinator import PlatformPathResolver

logger = logging.getLogger("dd_cleaner")

class DatasetCleaner:
    def __init__(self):
        self.working_dir: str = ""
        self.config: Dict[Any, Any] = {}
        self.paths: PlatformPathResolver = None

    def set_working_config(self, working_dir: str, config_path: str):
        abs_config_path = os.path.abspath(config_path)
        if not os.path.exists(abs_config_path):
            raise FileNotFoundError(f"Configuration file not found at: {abs_config_path}")
        
        with open(abs_config_path, 'r') as f:
            self.config = yaml.safe_load(f)
            
        if not os.path.isdir(working_dir):
            raise FileNotFoundError(f"Target data directory not found: {os.path.abspath(working_dir)}")
        self.working_dir = os.path.abspath(working_dir)
        
        # Instantiate the centralized Platform Abstraction Routing Engine
        self.paths = PlatformPathResolver(working_dir=self.working_dir, config=self.config)
        
        # Ensure our target destination folders exist prior to processing
        os.makedirs(self.paths.data_cleaner_dir, exist_ok=True)
        os.makedirs(self.paths.documents_dir, exist_ok=True)
        
        logger.info("Cleaner Context Initialized via unified Platform Abstraction routing.")

    def process_cleaning_pipeline(self):
        start_time = time.time()
        logger.info("Downstream cleaning pipeline sequence execution started.")
        
        # 1. Read metadata schema dynamically generated by the vector parser using path resolver properties
        meta_csv = self.paths.data_dictionary_csv_path
        if not os.path.exists(meta_csv):
            raise FileNotFoundError(f"Pipeline Handshake Failure: Data dictionary matrix missing at absolute path: {meta_csv}")
            
        df_meta = pd.read_csv(meta_csv)
        
        # Isolate target components dynamically via vector matrix metadata
        geo_rows = df_meta[df_meta['is_geographical'].astype(str).str.upper() == 'TRUE']
        geo_columns = geo_rows['attribute_name'].tolist()
        
        # 2. Load the dirty raw input dataset file directly via path resolver properties
        raw_data_path = self.paths.raw_data_input_path
        if not os.path.exists(raw_data_path):
            raise FileNotFoundError(f"Raw input data file missing at absolute path: {raw_data_path}")
            
        # Read all columns as string primitives to prevent auto-truncating zip leading zeros
        df_clean = pd.read_csv(raw_data_path, dtype=str)
        
        # 3. Vectorized Dynamic Scrub Blocks
        for col in geo_columns:
            if col in df_clean.columns:
                col_lower = col.lower()
                
                # Check for zip code parameters geometrically
                if 'zip' in col_lower or 'postal' in col_lower:
                    logger.info(f"Applying vectorized 5-digit zero-padding to column: {col}")
                    # Safely extract string parts before a decimal point to clear float artifacts
                    df_clean[col] = df_clean[col].astype(str).str.split('.').str[0]
                    df_clean[col] = df_clean[col].str.strip().str.zfill(5)
                
                # Check for text region metrics (City, Street, State, County, District)
                elif any(x in col_lower for x in ['city', 'street', 'state', 'county', 'district']):
                    logger.info(f"Applying vectorized title casing transformations to column: {col}")
                    df_clean[col] = df_clean[col].astype(str).str.strip().str.title()
        
        # 4. Commit clean tabular structures back to the resolved clean output destination path
        clean_filename = self.config.get("clean_output_filename", "sba_loans_clean.csv")
        clean_out_path = os.path.join(self.paths.data_cleaner_dir, clean_filename)
        df_clean.to_csv(clean_out_path, index=False)
        
        # 5. Generate metrics analytics markdown report layout
        duration = time.time() - start_time
        md_content = f"""# Data Cleaning Operations Report

## ⏱️ Execution Metrics
- **Timestamp**: {time.strftime('%Y-%m-%d %H:%M:%S')}
- **Duration**: {duration:.4f} seconds
- **Rows Processed**: {len(df_clean)}

## 🌍 Scrubbed Column Summary
- **Total Geographic Target Fields Modded**: {len(geo_columns)}
- **Processed Fields Sequence**: `{", ".join(geo_columns)}`
"""
        md_out = os.path.join(self.paths.documents_dir, "data_cleaning_summary.md")
        with open(md_out, "w", encoding="utf-8") as mf:
            mf.write(md_content)
            
        logger.info(f"Cleaning pipeline successfully finished in {duration:.4f} seconds.")
