"""Data quality profiling engine for null analysis and grounded inference context."""

import pandas as pd
import json
import logging
from datetime import datetime
from pathlib import Path
from typing import Dict, Optional

class DatasetDataProfiler:
    """
    Generates quality metrics and markdown reports for the dataset being cleaned.

    Attributes:
        output_path (Path): Destination for the markdown report.
    """

    def __init__(self, output_report_path: Path) -> None:
        """
        Initializes the profiler.

        Args:
            output_report_path (Path): Absolute path for report generation.
        """
        self.logger = logging.getLogger(__name__)
        self.output_path = output_report_path

    def generate_null_quality_report(self, df: pd.DataFrame, metadata_lookup: Optional[Dict[str, str]] = None) -> None:
        """
        Generates the profile stats and writes a markdown report to the workspace.

        Args:
            df (pd.DataFrame): The operational dataset to profile.
            metadata_lookup (dict, optional): Mapping of attribute names to logical types.
        """
        self.logger.info(f"📊 Generating Null Profile Report: {self.output_path.name}")
        
        stats = []
        json_bundle = {}
        for col in df.columns:
            series = df[col]
            null_count = int(series.isnull().sum())
            null_ratio = float(series.isnull().mean())
            cardinality = int(series.nunique())
            
            # mixed type detection for Assistant Rule 3
            non_null = series.dropna()
            is_mixed = "mixed" in pd.api.types.infer_dtype(non_null) if not non_null.empty else False

            # 🧼 DTYPE NORMALIZATION: Simplify pandas dtypes for the human report
            raw_dtype = str(series.dtype).lower()
            if "datetime" in raw_dtype:
                dtype = "datetime"
            elif "int" in raw_dtype or "float" in raw_dtype:
                dtype = "numeric"
            else:
                dtype = "str"
                
            # 🎯 RESOLUTION: Use the logical type from the parser metadata if available
            logical_type = metadata_lookup.get(col, dtype) if metadata_lookup else dtype
            
            # Task 4.1: Capture top 5 samples for Grounded Inference
            samples = [str(s) for s in series.dropna().unique()[:5]]
            samples_str = ", ".join(samples)

            stats.append({
                "Attribute": col,
                "Logical Type": logical_type,
                "Null Count": null_count,
                "Null %": f"{null_ratio:.2%}",
                "Unique": cardinality,
                "Samples": samples_str
            })
            
            json_bundle[col] = {
                "null_count": null_count,
                "null_ratio": null_ratio,
                "cardinality": cardinality,
                "logical_type": logical_type,
                "is_mixed_type": is_mixed,
                "samples": samples
            }

        ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        profile_df = pd.DataFrame(stats)
        self._write_markdown_report(profile_df, ts)
        
        # Wrap bundle in a structured format for the Assistant
        self._write_json_bundle({
            "columns": json_bundle,
            "row_count": len(df),
            "timestamp": ts
        })

    def _write_markdown_report(self, stats_df: pd.DataFrame, timestamp: str) -> None:
        """
        Persists the profile to the documents directory.

        Args:
            stats_df (pd.DataFrame): Tabular summary of null statistics.
            timestamp (str): Formatted generation time.
        """
        md_content = [
            "# 📊 Data Quality Profile & Null Analysis",
            f"**Report Generated**: `{timestamp}`",
            f"\n**Total Attributes Profiled**: {len(stats_df.index)}\n",
            "## Attribute Completeness Matrix",
            stats_df.to_markdown(index=False),
            "\n---",
            "\n*Generated by dd-parser-cleaner Integrity Engine.*"
        ]

        try:
            self.output_path.parent.mkdir(parents=True, exist_ok=True)
            with open(self.output_path, "w") as f:
                f.write("\n".join(md_content))
            self.logger.info(f"✅ Profile report saved to: {self.output_path}")
        except Exception as e:
            self.logger.error(f"❌ Failed to write profile report: {e}")

    def _write_json_bundle(self, data: dict) -> None:
        """
        Writes a lightweight JSON bundle for Grounded Inference.

        Args:
            data (dict): Structured metadata profile.
        """
        json_path = self.output_path.with_suffix(".json")
        try:
            with open(json_path, "w") as f:
                json.dump(data, f, indent=2)
            self.logger.info(f"✅ JSON metadata bundle saved to: {json_path.name}")
        except Exception as e:
            self.logger.error(f"❌ Failed to write JSON bundle: {e}")