"""Orchestration engine for the dataset cleaning pipeline."""

import sys
import logging
import yaml
import json
import pandas as pd
from pathlib import Path
from typing import Dict, Any, List
from rich.console import Console
from dd_common.path_coordinator import PathCoordinator

from dd_parser.rules import IntegrityEngine
from .assistant import CleaningAssistant
from .null_profiler import DatasetDataProfiler

class CleanerOrchestrator:
    """
    Manages the idempotent execution of data cleaning transformations.
    
    Implements the Phase 3 pipeline, coordinating between structural 
    assessment, AI-powered recommendations, and the transformation runner.

    Attributes:
        paths (PathCoordinator): Manages workspace resource routing.
        config (dict): The global project configuration.
        cleaner_cfg (dict): Cleaner-specific settings.
    """

    def __init__(self, path_coordinator: PathCoordinator) -> None:
        """
        Initializes the orchestrator.

        Args:
            path_coordinator (PathCoordinator): Authorized resource manager.
        """
        self.logger = logging.getLogger(__name__)
        self.paths = path_coordinator
        self.config = self.paths.config
        self.cleaner_cfg = self.config.get("cleaner", {})
        self.console = Console()

    def run_pipeline(self, action: str = "full") -> None:
        """
        Executes the sequence of cleaning gates and transformations.

        Args:
            action (str): Specific pipeline stage or 'full'.
        """
        self.logger.info("🚀 Starting Cleaner Pipeline...")

        # 🛡️ HANDSHAKE CHECK: Verify the parser-cleaner protocol file exists
        handshake = self.paths.handshake_path
        if not handshake.exists():
            self.console.print(f"\n[bold red]❌ Missing Handshake:[/bold red] The protocol file '[cyan]{handshake.name}[/cyan]' was not found.")
            self.console.print(f"[yellow]Expected location:[/yellow] [dim]{handshake.parent}[/dim]")
            self.console.print("\n[bold]Reason:[/bold] The cleaner requires semantic context generated by the parser to proceed.")
            self.console.print("[bold green]Action:[/bold green] Please run the [white]classify-entities[/white] command first.\n")
            return
        
        # 🎯 SEQUENTIAL EXECUTION: The 'full' pipeline runs 1, 2, and 3.
        active_actions = ["integrity", "profile", "assessment"] if action == "full" else [action]

        # --- 1. Handshake & Integrity Sync ---
        raw_path = Path(self.paths.raw_dataset_path)
        if not raw_path.exists():
            self.logger.error(f"Raw dataset missing at: {raw_path}")
            return

        # 🚀 PERFORMANCE: Attempt fast C-engine loading (defaults to comma separator).
        # Fallback to Python engine only if sniffing is required (sep=None).
        try:
            df = pd.read_csv(raw_path, engine='c', low_memory=False)
            self.logger.info(f"Loaded {raw_path.name} using high-performance C engine.")
        except Exception:
            self.logger.warning("C engine failed or delimiter is non-standard. Falling back to Python engine for sniffing...")
            df = pd.read_csv(raw_path, sep=None, engine='python')

        metadata_lookup = {}
        dd_path = Path(self.paths.data_dictionary_csv_path)

        if dd_path.exists():
            self.logger.info("Step 1: Handshake & Integrity Sync...")
            try:
                df_dict = pd.read_csv(dd_path, engine='c', low_memory=False)
            except Exception:
                df_dict = pd.read_csv(dd_path, sep=None, engine='python')

            dd_attributes = df_dict["attribute_name"].dropna().tolist()
            bridge = IntegrityEngine.evaluate_bridge(dd_attributes, list(df.columns))
            self.logger.info(f"🌉 Bridge Evaluation: {len(bridge['operational'])} Operational, {len(bridge['orphans'])} Orphans")

            df = df[bridge['operational']].copy()
            attr_col = "attribute_name" if "attribute_name" in df_dict.columns else df_dict.columns[0]
            metadata_lookup = df_dict.set_index(attr_col)["logical_type"].to_dict()

        # --- 2. Null Profiling ---
        if "profile" in active_actions:
            self.console.print("\n[bold yellow]Step 2: Generating Data Quality Profile...[/bold yellow]")
            profiler = DatasetDataProfiler(Path(self.paths.profiling_report_path))
            profiler.generate_null_quality_report(df, metadata_lookup=metadata_lookup)
            self.console.print(f"[bold green]✅ Null Profile Generated![/bold green] See: [cyan]{self.paths.profiling_report_path}[/cyan]")

        # --- 3. Assessment & Recommendations ---
        if "assessment" in active_actions:
            self.console.print("\n[bold yellow]Step 3: Generating Cleaning Recommendations...[/bold yellow]")
            profile_json = Path(self.paths.profiling_report_path).with_suffix(".json")
            
            if not profile_json.resolve().exists():
                self.logger.warning("Profile JSON missing. Running profiler automatically.")
                profiler = DatasetDataProfiler(Path(self.paths.profiling_report_path))
                profiler.generate_null_quality_report(df, metadata_lookup=metadata_lookup)

            self.assistant = CleaningAssistant(self.config, profile_json, dd_path)
            self.assistant.generate_recommendations()
            self.assistant.write_artifacts(self.paths.cleaner_narrative_directory)
            
            report_path = self.paths.cleaner_narrative_directory / "cleaning_recommendations.md"
            self.console.print(f"\n[bold green]✅ Success: Diagnostic suite concluded.[/bold green]")
            self.console.print(f"📄 Review Recommendations: [cyan]{report_path}[/cyan]")

        # --- 4. Dataset Persistence ---
        # Persist the synchronized/subsetted dataframe to the authoritative output path.
        output_path = self.paths.clean_dataset_output_path
        self.logger.info(f"💾 Persisting synchronized dataset to: {output_path}")
        df.to_csv(output_path, index=False)
        self.console.print(f"[bold green]✅ Dataset Exported:[/bold green] [cyan]{output_path}[/cyan]")